CREATE TABLE IF NOT EXISTS notes (
  local_id INT PRIMARY KEY AUTOINCREMENT,
  id INT UNIQUE,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  is_favourite BOOLEAN NOT NULL DEFAULT 0,
  created_at INT NOT NULL DEFAULT UNIXEPOCH('now'),
  last_updated_at INT NOT NULL DEFAULT UNIXEPOCH('now'),
  user_id TEXT
);
